apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mydatabase
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    env: db
  type: NodePort
status:
  loadBalancer: {}
